/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rcsasScreens;

/**
 *
 * @author sarah
 */
public class Admin_Dashboard extends javax.swing.JFrame {


    public Admin_Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ExitBtn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        CoachRecordMI = new javax.swing.JMenuItem();
        SportRecordMI = new javax.swing.JMenuItem();
        SportScheduleMI = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        DisplayCoachMI = new javax.swing.JMenuItem();
        DisplaySportMI = new javax.swing.JMenuItem();
        DisplayStudentMI = new javax.swing.JMenuItem();
        ScheduleMI = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        SearchCoachMI = new javax.swing.JMenuItem();
        SearchStudentMI = new javax.swing.JMenuItem();
        SearchSportMI = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(637, 328));

        ExitBtn1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ExitBtn1.setText("Exit");
        ExitBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtn1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Admin's Dashboard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitBtn1)
                .addGap(47, 47, 47))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel1)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(88, 88, 88)
                .addComponent(ExitBtn1)
                .addGap(47, 47, 47))
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(200, 50));

        jMenu1.setText("Add");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        CoachRecordMI.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        CoachRecordMI.setText("Coach Record");
        CoachRecordMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoachRecordMIActionPerformed(evt);
            }
        });
        jMenu1.add(CoachRecordMI);

        SportRecordMI.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        SportRecordMI.setText("Sport Record");
        SportRecordMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SportRecordMIActionPerformed(evt);
            }
        });
        jMenu1.add(SportRecordMI);

        SportScheduleMI.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        SportScheduleMI.setText("Sport Schedule");
        SportScheduleMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SportScheduleMIActionPerformed(evt);
            }
        });
        jMenu1.add(SportScheduleMI);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Display");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        DisplayCoachMI.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        DisplayCoachMI.setText("Coach Records");
        DisplayCoachMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayCoachMIActionPerformed(evt);
            }
        });
        jMenu2.add(DisplayCoachMI);

        DisplaySportMI.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        DisplaySportMI.setText("Sport Records");
        DisplaySportMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplaySportMIActionPerformed(evt);
            }
        });
        jMenu2.add(DisplaySportMI);

        DisplayStudentMI.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        DisplayStudentMI.setText("Students List");
        DisplayStudentMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayStudentMIActionPerformed(evt);
            }
        });
        jMenu2.add(DisplayStudentMI);

        ScheduleMI.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        ScheduleMI.setText("Sport Schedule");
        ScheduleMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScheduleMIActionPerformed(evt);
            }
        });
        jMenu2.add(ScheduleMI);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Search");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        SearchCoachMI.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        SearchCoachMI.setText("Coach");
        SearchCoachMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCoachMIActionPerformed(evt);
            }
        });
        jMenu3.add(SearchCoachMI);

        SearchStudentMI.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        SearchStudentMI.setText("Student");
        SearchStudentMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchStudentMIActionPerformed(evt);
            }
        });
        jMenu3.add(SearchStudentMI);

        SearchSportMI.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        SearchSportMI.setText("Sport");
        SearchSportMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchSportMIActionPerformed(evt);
            }
        });
        jMenu3.add(SearchSportMI);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtn1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitBtn1ActionPerformed

    private void SportRecordMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SportRecordMIActionPerformed
        this.setVisible(false);
        Add_Sport asp = new Add_Sport();
        asp.setLocation(500,200);
        asp.setVisible(true);     
    }//GEN-LAST:event_SportRecordMIActionPerformed

    private void DisplaySportMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplaySportMIActionPerformed
        this.setVisible(false);
        Display_Sport ds = new Display_Sport();
        ds.setLocation(500,200);
        ds.setVisible(true);
    }//GEN-LAST:event_DisplaySportMIActionPerformed

    private void SearchCoachMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCoachMIActionPerformed
        this.setVisible(false);
        Search_Coach sc = new Search_Coach();
        sc.setLocation(500,200);
        sc.setVisible(true);
    }//GEN-LAST:event_SearchCoachMIActionPerformed

    private void SearchStudentMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchStudentMIActionPerformed
        this.setVisible(false);
        Search_Student sst = new Search_Student();
        sst.setLocation(500,200);
        sst.setVisible(true);
    }//GEN-LAST:event_SearchStudentMIActionPerformed

    private void CoachRecordMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoachRecordMIActionPerformed
        this.setVisible(false);
        Add_Coach ac = new Add_Coach();
        ac.setLocation(500,200);
        ac.setVisible(true);
    }//GEN-LAST:event_CoachRecordMIActionPerformed

    private void DisplayCoachMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayCoachMIActionPerformed
        this.setVisible(false);
        Display_Coach dc = new Display_Coach();
        dc.setLocation(500,200);
        dc.setVisible(true);
    }//GEN-LAST:event_DisplayCoachMIActionPerformed

    private void DisplayStudentMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayStudentMIActionPerformed
        this.setVisible(false);
        Display_Student dst = new Display_Student();
        dst.setLocation(500,200);
        dst.setVisible(true);
    }//GEN-LAST:event_DisplayStudentMIActionPerformed

    private void SearchSportMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchSportMIActionPerformed
        this.setVisible(false);
        Search_Sport ssp = new Search_Sport();
        ssp.setLocation(500,200);
        ssp.setVisible(true);
    }//GEN-LAST:event_SearchSportMIActionPerformed

    private void SportScheduleMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SportScheduleMIActionPerformed
        this.setVisible(false);
        Add_SportSchedule ac = new Add_SportSchedule();
        ac.setLocation(500,200);
        ac.setVisible(true);
    }//GEN-LAST:event_SportScheduleMIActionPerformed

    private void ScheduleMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScheduleMIActionPerformed
        this.setVisible(false);
        Display_Schedule dc = new Display_Schedule();
        dc.setLocation(500,200);
        dc.setVisible(true);
    }//GEN-LAST:event_ScheduleMIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CoachRecordMI;
    private javax.swing.JMenuItem DisplayCoachMI;
    private javax.swing.JMenuItem DisplaySportMI;
    private javax.swing.JMenuItem DisplayStudentMI;
    private javax.swing.JButton ExitBtn1;
    private javax.swing.JMenuItem ScheduleMI;
    private javax.swing.JMenuItem SearchCoachMI;
    private javax.swing.JMenuItem SearchSportMI;
    private javax.swing.JMenuItem SearchStudentMI;
    private javax.swing.JMenuItem SportRecordMI;
    private javax.swing.JMenuItem SportScheduleMI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
