/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rcsasScreens;

import classes.Coach;
import classes.Sport;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author sarah
 */
public class Display_Coach extends javax.swing.JFrame {

    /**
     * Creates new form Display_Coach
     */
    
    DefaultTableModel model;
    public Display_Coach() {
        initComponents();
        model = (DefaultTableModel)tblDisplayCoaches.getModel();
    }
    
    
    
    private void fillTxt(Coach coach) {
        NameTxt.setText(coach.getCoachName());
        DJTxt.setText(coach.getDateJoined());
        HourlyRateTxt.setText(coach.getHourlyRate());
        PhoneTxt.setText(coach.getPhone());
        AddressTxt.setText(coach.getAddress());
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DisplayCoachBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisplayCoaches = new javax.swing.JTable();
        SortCoachBtn = new javax.swing.JButton();
        ModifyCoachBtn = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        DJTxt = new javax.swing.JTextField();
        HourlyRateTxt = new javax.swing.JTextField();
        PhoneTxt = new javax.swing.JTextField();
        AddressTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        RatingComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("All Coaches");

        DisplayCoachBtn.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        DisplayCoachBtn.setText("Display");
        DisplayCoachBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayCoachBtnActionPerformed(evt);
            }
        });

        tblDisplayCoaches.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CoachID", "Rating", "Name", "Phone", "Sport Name", "DateJoined", "Hourly Rate", "Address"
            }
        ));
        tblDisplayCoaches.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDisplayCoachesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDisplayCoaches);

        SortCoachBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        SortCoachBtn.setText("Sort Coach");
        SortCoachBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortCoachBtnActionPerformed(evt);
            }
        });

        ModifyCoachBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ModifyCoachBtn.setText("Modify");
        ModifyCoachBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyCoachBtnActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton8.setText("Exit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Coach Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Date Joined:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Hourly Rate:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Phone:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Address:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Rating:");

        RatingComboBox.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        RatingComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(DisplayCoachBtn)
                                .addGap(18, 18, 18)
                                .addComponent(SortCoachBtn))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(HourlyRateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addGap(18, 18, 18)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(PhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RatingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ModifyCoachBtn)))
                        .addGap(76, 76, 76))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DisplayCoachBtn)
                    .addComponent(SortCoachBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(DJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(AddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(HourlyRateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(RatingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModifyCoachBtn))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.setVisible(false);
        Admin_Dashboard ad = new Admin_Dashboard();
        ad.setLocation(500,200);
        ad.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void DisplayCoachBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayCoachBtnActionPerformed
        
        String filePath = "coach.txt";
        File file = new File(filePath);
        
        try{
            BufferedReader br = new BufferedReader(new FileReader(file));
            Object[] tableLines = br.lines().toArray();

            for(int i = 0; i< tableLines.length; i++){
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split("/");
                model.addRow(dataRow);
            }
            
        } catch(Exception ex){
            Logger.getLogger(Display_Student.class.getName()).log(Level.SEVERE,null, ex);
        }
    }//GEN-LAST:event_DisplayCoachBtnActionPerformed

    private void SortCoachBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortCoachBtnActionPerformed
        
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(tblDisplayCoaches.getModel());
        tblDisplayCoaches.setRowSorter(sorter);

        List<RowSorter.SortKey> sortKeys = new ArrayList<>(25);
        sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
        sorter.setSortKeys(sortKeys);
    }//GEN-LAST:event_SortCoachBtnActionPerformed

    private void ModifyCoachBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyCoachBtnActionPerformed
        if(this.NameTxt.getText().isEmpty() || this.DJTxt.getText().isEmpty() || 
                this.HourlyRateTxt.getText().isEmpty() || this.PhoneTxt.getText().isEmpty() || this.AddressTxt.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this, "All Fields Required", "Empty Fields", JOptionPane.ERROR_MESSAGE);
            
        } else {
            if(tblDisplayCoaches.getSelectedRow() >= 0){
                int row = tblDisplayCoaches.getSelectedRow();
                int coachID = Integer.parseInt((String)model.getValueAt(row, 0));
                int rating = Integer.parseInt((String)model.getValueAt(row, 1));
                String coachname = (String)model.getValueAt(row, 2);
                String phone = (String)model.getValueAt(row, 3);
                String sportname = (String)model.getValueAt(row, 4);
                String datejoined = (String)model.getValueAt(row, 5);
                String hourlyrate = (String)model.getValueAt(row, 6);
                String address = (String)model.getValueAt(row, 7);

             
                
                Coach coachEdit = new Coach(coachID, rating, coachname, phone, sportname, datejoined, hourlyrate, address);
                Coach editedCoach;
                editedCoach = new Coach();
                editedCoach.setCoachID(coachID);
                editedCoach.setCoachName(this.NameTxt.getText());
                editedCoach.setDateJoined(this.DJTxt.getText());
                editedCoach.setHourlyRate(this.HourlyRateTxt.getText());
                editedCoach.setPhone(this.PhoneTxt.getText());
                editedCoach.setAddress(this.AddressTxt.getText());
                editedCoach.setSportName(sportname);
                editedCoach.setRating(Integer.parseInt(this.RatingComboBox.getSelectedItem().toString().trim()));
                
                coachEdit.editCoach(editedCoach);

                JOptionPane.showMessageDialog(this, "Record Saved", "Success", JOptionPane.INFORMATION_MESSAGE);
                
                NameTxt.setText("");
                DJTxt.setText("");
                HourlyRateTxt.setText("");
                PhoneTxt.setText("");
                AddressTxt.setText("");
                
     
            } else {
                JOptionPane.showMessageDialog(this, "Please select a record!", "Error", JOptionPane.ERROR_MESSAGE);
                
            }
        }
        model.setRowCount(0);
        

        
    }//GEN-LAST:event_ModifyCoachBtnActionPerformed

    private void tblDisplayCoachesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDisplayCoachesMouseClicked
        Coach coach = TblClick();
        fillTxt(coach);
    }//GEN-LAST:event_tblDisplayCoachesMouseClicked

    
    private Coach TblClick() {
        int row = tblDisplayCoaches.getSelectedRow();
        int coachID = Integer.parseInt((String)model.getValueAt(row, 0));
        int rating = Integer.parseInt((String)model.getValueAt(row, 1));
        String coachname = (String)model.getValueAt(row, 2);
        String phone = (String)model.getValueAt(row, 3);
        String sportname = (String)model.getValueAt(row, 4);
        String datejoined = (String)model.getValueAt(row, 5);
        String hourlyrate = (String)model.getValueAt(row, 6);
        String address = (String)model.getValueAt(row, 7);

        
        
        Coach ch = new Coach();
        ch.setCoachID(coachID);
        ch.setCoachName(coachname);
        ch.setDateJoined(datejoined);
        ch.setHourlyRate(hourlyrate);
        ch.setPhone(phone);
        ch.setAddress(address);
        ch.setSportName(sportname);
        ch.setRating(rating);
        fillTxt(ch);
        return ch;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display_Coach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display_Coach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display_Coach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display_Coach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display_Coach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTxt;
    private javax.swing.JTextField DJTxt;
    private javax.swing.JButton DisplayCoachBtn;
    private javax.swing.JTextField HourlyRateTxt;
    private javax.swing.JButton ModifyCoachBtn;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JTextField PhoneTxt;
    private javax.swing.JComboBox<String> RatingComboBox;
    private javax.swing.JButton SortCoachBtn;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDisplayCoaches;
    // End of variables declaration//GEN-END:variables
}
