/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rcsasScreens;

import classes.Coach;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * 
 * @author sarah
 */
public class Search_Coach extends javax.swing.JFrame {

    /**
     * Creates new form Search_Coach
     */
    DefaultTableModel model;
    public Search_Coach() {
        initComponents();
        model = (DefaultTableModel)tblDisplayCoach.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SearchCoachIDTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        SearchCoachRatingTxt = new javax.swing.JTextField();
        SearchCIDBtn = new javax.swing.JButton();
        SearchCRBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisplayCoach = new javax.swing.JTable();
        BackBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ClearTableBtn = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Search Coach");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Search by Coach ID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Search by Coach Rating:");

        SearchCIDBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        SearchCIDBtn.setText("Search");
        SearchCIDBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCIDBtnActionPerformed(evt);
            }
        });

        SearchCRBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        SearchCRBtn.setText("Search");
        SearchCRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCRBtnActionPerformed(evt);
            }
        });

        tblDisplayCoach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Coach ID", "Rating", "Coach Name", "Phone Number", "Sport Name", "Date Joined", "Hourly Rate", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDisplayCoach);

        BackBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.setActionCommand("BackBtn");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ClearTableBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ClearTableBtn.setText("Clear");
        ClearTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearTableBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(jLabel2))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SearchCoachRatingTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                            .addComponent(SearchCoachIDTxt))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SearchCIDBtn)
                            .addComponent(SearchCRBtn))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ClearTableBtn)
                .addGap(35, 35, 35)
                .addComponent(BackBtn)
                .addGap(30, 30, 30)
                .addComponent(jButton2)
                .addGap(69, 69, 69))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(386, 386, 386)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(SearchCoachIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchCIDBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchCRBtn)
                    .addComponent(SearchCoachRatingTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackBtn)
                    .addComponent(jButton2)
                    .addComponent(ClearTableBtn))
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        this.setVisible(false);
        Admin_Dashboard adb = new Admin_Dashboard();
        adb.setLocation(500,200);
        adb.setVisible(true);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void SearchCIDBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCIDBtnActionPerformed
        
       
        if(this.SearchCoachIDTxt.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Search field cannot be empty!", "Empty Fields", JOptionPane.ERROR_MESSAGE);
        } else {
            Coach c1 = new Coach();
            c1.setCoachID(Integer.parseInt(SearchCoachIDTxt.getText()));
            if(c1.searchCoachbyID().getCoachName()!= null){
                
                c1 = c1.searchCoachbyID();
                model.getDataVector().removeAllElements();
                model.fireTableDataChanged();
                model.addRow(new String[]{
                    Integer.toString(c1.getCoachID()),
                    Integer.toString(c1.getRating()),
                    c1.getCoachName(),
                    c1.getPhone(),
                    c1.getSportName(),
                    c1.getDateJoined(),
                    c1.getHourlyRate(),
                    c1.getAddress()                   
                });
                JOptionPane.showMessageDialog(this, "Match Found", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                model.getDataVector().removeAllElements();
                model.fireTableDataChanged();
                JOptionPane.showMessageDialog(this, "No Match Found", "No Records", JOptionPane.INFORMATION_MESSAGE);
                System.out.println(Coach.getAllCoach().toString());
            }
        }

    }//GEN-LAST:event_SearchCIDBtnActionPerformed

    private void SearchCRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCRBtnActionPerformed
            
        if(this.SearchCoachRatingTxt.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Search field cannot be empty!", "Empty Fields", JOptionPane.ERROR_MESSAGE);
        } else {
            Coach c1 = new Coach();
            c1.setRating(Integer.parseInt(SearchCoachRatingTxt.getText()));
            //
            if(c1.searchCoachbyRating().getCoachName()!= null){
                c1 = c1.searchCoachbyRating();
                model.getDataVector().removeAllElements();
                model.fireTableDataChanged();
                model.addRow(new String[]{
                    Integer.toString(c1.getCoachID()),
                    Integer.toString(c1.getRating()),
                    c1.getCoachName(),
                    c1.getPhone(),
                    c1.getSportName(),
                    c1.getDateJoined(),
                    c1.getHourlyRate(),
                    c1.getAddress()             
                });
                JOptionPane.showMessageDialog(this, "Match Found", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                model.getDataVector().removeAllElements();
                model.fireTableDataChanged();
                JOptionPane.showMessageDialog(this, "No Match Found", "No Records", JOptionPane.INFORMATION_MESSAGE);
                System.out.println(Coach.getAllCoach().toString());
            }
            
        }
        

    }//GEN-LAST:event_SearchCRBtnActionPerformed

    private void ClearTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearTableBtnActionPerformed
        model.setRowCount(0);
    }//GEN-LAST:event_ClearTableBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search_Coach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search_Coach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search_Coach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search_Coach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search_Coach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton ClearTableBtn;
    private javax.swing.JButton SearchCIDBtn;
    private javax.swing.JButton SearchCRBtn;
    private javax.swing.JTextField SearchCoachIDTxt;
    private javax.swing.JTextField SearchCoachRatingTxt;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDisplayCoach;
    // End of variables declaration//GEN-END:variables
}
