/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rcsasScreens;

/**
 *
 * @author sarah
 */
public class Student_Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form StudentDashboard
     */
    public Student_Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ExitBtn = new javax.swing.JButton();
        StudentMenuBar = new javax.swing.JMenuBar();
        ViewTab = new javax.swing.JMenu();
        ScheduleMenuItem = new javax.swing.JMenuItem();
        CoachDetailsMenuItem = new javax.swing.JMenuItem();
        AccountTab = new javax.swing.JMenu();
        ProfileMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Student's Dashboard");

        ExitBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ExitBtn.setText("Exit");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(82, 82, 82)
                .addComponent(ExitBtn)
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(249, Short.MAX_VALUE)
                .addComponent(ExitBtn)
                .addGap(46, 46, 46))
        );

        StudentMenuBar.setPreferredSize(new java.awt.Dimension(200, 50));

        ViewTab.setText("View");
        ViewTab.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        ScheduleMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        ScheduleMenuItem.setText("Sport Schedule");
        ScheduleMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScheduleMenuItemActionPerformed(evt);
            }
        });
        ViewTab.add(ScheduleMenuItem);

        CoachDetailsMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        CoachDetailsMenuItem.setText("Coach Details");
        CoachDetailsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoachDetailsMenuItemActionPerformed(evt);
            }
        });
        ViewTab.add(CoachDetailsMenuItem);

        StudentMenuBar.add(ViewTab);

        AccountTab.setText("My Account");
        AccountTab.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        ProfileMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        ProfileMenuItem.setText("View Profile");
        ProfileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileMenuItemActionPerformed(evt);
            }
        });
        AccountTab.add(ProfileMenuItem);

        StudentMenuBar.add(AccountTab);

        jMenu1.setText("Feedback");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jMenuItem1.setText("Feedback and Rating");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        StudentMenuBar.add(jMenu1);

        setJMenuBar(StudentMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ScheduleMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScheduleMenuItemActionPerformed
        this.setVisible(false);
        Student_SportSchedule sss = new Student_SportSchedule();
        sss.setLocation(500,200);
        sss.setVisible(true);
    }//GEN-LAST:event_ScheduleMenuItemActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void CoachDetailsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoachDetailsMenuItemActionPerformed
        this.setVisible(false);
        Student_CoachDetails scd = new Student_CoachDetails();
        scd.setLocation(500,200);
        scd.setVisible(true);
    }//GEN-LAST:event_CoachDetailsMenuItemActionPerformed

    private void ProfileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileMenuItemActionPerformed
        this.setVisible(false);
        Student_Profile sp = new Student_Profile();
        sp.setLocation(500,200);
        sp.setVisible(true);
    }//GEN-LAST:event_ProfileMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setVisible(false);
        Student_Feedback sp = new Student_Feedback();
        sp.setLocation(500,200);
        sp.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AccountTab;
    private javax.swing.JMenuItem CoachDetailsMenuItem;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JMenuItem ProfileMenuItem;
    private javax.swing.JMenuItem ScheduleMenuItem;
    private javax.swing.JMenuBar StudentMenuBar;
    private javax.swing.JMenu ViewTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
